### ISSUE TITLE
Horizontal scrolling is not working

### ISSUE THREAD

**Issue by hartenthaler** [jchue/argon-webtrees-theme#9] opened 2021-04-08 23:17 UTC
If the relationship path is broader than my screen width, then there is a horizontal scrolling bar. This is the case for all webtrees themes including Argon. But when I'm scrolling to the right, normally this part of the relationship path is shown. When using Argon there is only white space.
![Screenshot (241)_LI](https://user-images.githubusercontent.com/6324175/114107328-11412180-98d1-11eb-81d2-d4ec292b2183.jpg)

**Comment by jchue** [comment] 2021-04-15 01:03
I believe this is because overflow handling was missing for the chart, which was added in 6cf9fe40206cb09af88449c85f22a1adf1b256f7. @hartenthaler, could you see if the issue is fixed in the latest version?

**Comment by hartenthaler** [comment] 2021-04-15 10:54
Yes it is fixed! Thank you!

**Closed** 2021-04-15 10:54 UTC
